language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install pip -U
  - pip install -r requirements.txt
  - pip-compile {{cookiecutter.project_name}}/requirements.in
  - pip install -r {{cookiecutter.project_name}}/requirements.txt

script:
  - ./runtests.sh
