language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install pip -U
  - pip install -r requirements.txt
  - pip install -r {{cookiecutter.project_name}}/requirements.in

script:
  - ./runtests.sh
